// <auto-generated />
using System;
using Amrod_E_Commerce.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amrod_E_Commerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328071308_Seed100Rows")]
    partial class Seed100Rows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a539612d-8a1b-4c41-b75e-95b9fc1fa704"),
                            Description = "Description for Product 1",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 1",
                            Price = 509.76m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("1c770d86-38da-4444-95c2-0e502a79ca91"),
                            Description = "Description for Product 2",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 2",
                            Price = 674.23m,
                            Stock = 84
                        },
                        new
                        {
                            Id = new Guid("685c330e-bba0-483a-a569-2e0b367e2dcb"),
                            Description = "Description for Product 3",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 3",
                            Price = 37.57m,
                            Stock = 49
                        },
                        new
                        {
                            Id = new Guid("786abf70-08cf-474c-a6a4-77fcb1780836"),
                            Description = "Description for Product 4",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 4",
                            Price = 984.19m,
                            Stock = 75
                        },
                        new
                        {
                            Id = new Guid("688c93d3-5871-44ee-be3a-8e32438ac271"),
                            Description = "Description for Product 5",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 5",
                            Price = 558.80m,
                            Stock = 45
                        },
                        new
                        {
                            Id = new Guid("9a167db1-9cb0-49d3-b50e-a9104c282d7f"),
                            Description = "Description for Product 6",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 6",
                            Price = 836.26m,
                            Stock = 83
                        },
                        new
                        {
                            Id = new Guid("655e9743-2592-4505-8c2a-a3dce31285c9"),
                            Description = "Description for Product 7",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 7",
                            Price = 91.20m,
                            Stock = 89
                        },
                        new
                        {
                            Id = new Guid("40cc1aaf-ae8c-48e6-9edc-14a1ba06514c"),
                            Description = "Description for Product 8",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 8",
                            Price = 788.33m,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("ac006d5d-21ca-4da2-8f50-3ced0523bc9e"),
                            Description = "Description for Product 9",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 9",
                            Price = 452.35m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("e63c8526-5f2d-40b0-a9ec-d43252f9df20"),
                            Description = "Description for Product 10",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 10",
                            Price = 386.78m,
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("a87ac403-00bf-4dcb-a2d5-d6bb9c5f9460"),
                            Description = "Description for Product 11",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 11",
                            Price = 214.84m,
                            Stock = 92
                        },
                        new
                        {
                            Id = new Guid("e7564e36-8705-4072-91f0-cdd49ebdf291"),
                            Description = "Description for Product 12",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 12",
                            Price = 209.29m,
                            Stock = 97
                        },
                        new
                        {
                            Id = new Guid("09095c62-7b60-4a27-a13b-870f4b68608d"),
                            Description = "Description for Product 13",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 13",
                            Price = 10.42m,
                            Stock = 57
                        },
                        new
                        {
                            Id = new Guid("5ed40460-aa92-4a3e-8ef5-2ba8d2321a11"),
                            Description = "Description for Product 14",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 14",
                            Price = 913.99m,
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("037f6a2d-bd1f-4968-abd6-e2951ca64ac8"),
                            Description = "Description for Product 15",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 15",
                            Price = 697.07m,
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("97e6095d-b62d-4127-b580-612231d84c9f"),
                            Description = "Description for Product 16",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 16",
                            Price = 82.62m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("40ca4120-28b5-4a21-a9d3-955d592ace98"),
                            Description = "Description for Product 17",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 17",
                            Price = 167.14m,
                            Stock = 79
                        },
                        new
                        {
                            Id = new Guid("1996ee07-cdeb-4aa5-b2b9-8a549a9a5652"),
                            Description = "Description for Product 18",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 18",
                            Price = 778.49m,
                            Stock = 95
                        },
                        new
                        {
                            Id = new Guid("d019b3ff-d9c6-4990-8744-ec338d8177f0"),
                            Description = "Description for Product 19",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 19",
                            Price = 897.20m,
                            Stock = 63
                        },
                        new
                        {
                            Id = new Guid("ada894d2-baca-4d14-9cca-7fabad3f0064"),
                            Description = "Description for Product 20",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 20",
                            Price = 700.44m,
                            Stock = 91
                        },
                        new
                        {
                            Id = new Guid("2d215943-f0d5-47f6-8d77-2acac457df25"),
                            Description = "Description for Product 21",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 21",
                            Price = 854.15m,
                            Stock = 95
                        },
                        new
                        {
                            Id = new Guid("e3b13380-2756-4ac3-9fc3-db866421848e"),
                            Description = "Description for Product 22",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 22",
                            Price = 328.63m,
                            Stock = 85
                        },
                        new
                        {
                            Id = new Guid("95261416-7181-4efe-a0e0-2bb73c6e60f0"),
                            Description = "Description for Product 23",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 23",
                            Price = 999.48m,
                            Stock = 65
                        },
                        new
                        {
                            Id = new Guid("8b642753-c5bf-4142-836b-da5bf6678f8f"),
                            Description = "Description for Product 24",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 24",
                            Price = 652.94m,
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("cfa452b9-e571-48c2-ae62-00143475ae22"),
                            Description = "Description for Product 25",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 25",
                            Price = 673.13m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("66284aab-7a0a-44b0-965e-1b884d3f50a8"),
                            Description = "Description for Product 26",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 26",
                            Price = 68.48m,
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("e8d3d2a6-2c5c-4be4-adec-bb8afc184ac7"),
                            Description = "Description for Product 27",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 27",
                            Price = 579.20m,
                            Stock = 49
                        },
                        new
                        {
                            Id = new Guid("6ab13456-89f6-4bc9-b919-22809acdcf51"),
                            Description = "Description for Product 28",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 28",
                            Price = 766.65m,
                            Stock = 56
                        },
                        new
                        {
                            Id = new Guid("5ff705b7-ec20-475f-b7c6-2168e02b206b"),
                            Description = "Description for Product 29",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 29",
                            Price = 775.70m,
                            Stock = 94
                        },
                        new
                        {
                            Id = new Guid("3de66135-ddd4-43f8-92e1-7178bf1f3822"),
                            Description = "Description for Product 30",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 30",
                            Price = 627.24m,
                            Stock = 68
                        },
                        new
                        {
                            Id = new Guid("ebe8f767-538e-4b61-b820-aa10095cac9a"),
                            Description = "Description for Product 31",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 31",
                            Price = 328.24m,
                            Stock = 86
                        },
                        new
                        {
                            Id = new Guid("af439fa4-d207-4bfb-8f58-3a9b15ddbf4e"),
                            Description = "Description for Product 32",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 32",
                            Price = 519.79m,
                            Stock = 61
                        },
                        new
                        {
                            Id = new Guid("570eddb7-a3a9-419c-b21a-23e9306d5005"),
                            Description = "Description for Product 33",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 33",
                            Price = 580.34m,
                            Stock = 98
                        },
                        new
                        {
                            Id = new Guid("2a78bef0-67c6-4719-aaba-85a34e6453f4"),
                            Description = "Description for Product 34",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 34",
                            Price = 663.99m,
                            Stock = 72
                        },
                        new
                        {
                            Id = new Guid("352c05dc-841b-47a9-a4ec-ec64cf91d543"),
                            Description = "Description for Product 35",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 35",
                            Price = 61.82m,
                            Stock = 36
                        },
                        new
                        {
                            Id = new Guid("a02c967b-9f90-4812-b2f4-4d9f6d2d1d45"),
                            Description = "Description for Product 36",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 36",
                            Price = 218.64m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("c37ac9ed-5fa2-484b-ad54-0e73b5b32365"),
                            Description = "Description for Product 37",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 37",
                            Price = 806.75m,
                            Stock = 89
                        },
                        new
                        {
                            Id = new Guid("677d2f43-f14c-42c7-845e-0124e6a154b3"),
                            Description = "Description for Product 38",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 38",
                            Price = 345.42m,
                            Stock = 47
                        },
                        new
                        {
                            Id = new Guid("da2935cb-dd92-49df-bbcc-116932ca60ce"),
                            Description = "Description for Product 39",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 39",
                            Price = 175.52m,
                            Stock = 24
                        },
                        new
                        {
                            Id = new Guid("4f25dcd4-a3b1-43ed-9c4a-d9b505696b2a"),
                            Description = "Description for Product 40",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 40",
                            Price = 304.11m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("a0511ffe-5a09-499a-99bb-df4a9086c8cf"),
                            Description = "Description for Product 41",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 41",
                            Price = 742.38m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("36f8e3b4-d75e-4d07-9e29-88ea9a7cd289"),
                            Description = "Description for Product 42",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 42",
                            Price = 137.14m,
                            Stock = 31
                        },
                        new
                        {
                            Id = new Guid("b0a3e29f-a2e2-4665-af2e-7a3ed35e1111"),
                            Description = "Description for Product 43",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 43",
                            Price = 762.30m,
                            Stock = 31
                        },
                        new
                        {
                            Id = new Guid("6345a15f-76b6-44ba-a85e-14509a760ced"),
                            Description = "Description for Product 44",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 44",
                            Price = 424.53m,
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("40e457aa-4fe5-4475-bd31-b57886078624"),
                            Description = "Description for Product 45",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 45",
                            Price = 62.84m,
                            Stock = 57
                        },
                        new
                        {
                            Id = new Guid("68c00525-5204-4b1c-bcf8-353cf7711493"),
                            Description = "Description for Product 46",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 46",
                            Price = 570.63m,
                            Stock = 28
                        },
                        new
                        {
                            Id = new Guid("6e05e78a-dd41-4198-84eb-f700fa196a95"),
                            Description = "Description for Product 47",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 47",
                            Price = 560.87m,
                            Stock = 68
                        },
                        new
                        {
                            Id = new Guid("ab9d2dc8-6ded-4518-aab4-7e5b617fd24d"),
                            Description = "Description for Product 48",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 48",
                            Price = 625.84m,
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("853436e5-a858-44c5-bba5-e24f1c5b9152"),
                            Description = "Description for Product 49",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 49",
                            Price = 300.00m,
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("551dbfe4-c891-43ff-b453-c429839a46dd"),
                            Description = "Description for Product 50",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 50",
                            Price = 725.94m,
                            Stock = 73
                        },
                        new
                        {
                            Id = new Guid("8b8b7c92-8362-4c6f-be2e-ff6cb5deaf8b"),
                            Description = "Description for Product 51",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 51",
                            Price = 710.47m,
                            Stock = 98
                        },
                        new
                        {
                            Id = new Guid("04d9242a-22a8-4ac6-851b-2abb29e6ce44"),
                            Description = "Description for Product 52",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 52",
                            Price = 133.40m,
                            Stock = 83
                        },
                        new
                        {
                            Id = new Guid("6acc26b5-a0fb-4d68-885c-8d47e4173fd7"),
                            Description = "Description for Product 53",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 53",
                            Price = 151.75m,
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("6d0a3e92-0bcb-4e6f-a5a8-9cb8b9e221a6"),
                            Description = "Description for Product 54",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 54",
                            Price = 328.89m,
                            Stock = 96
                        },
                        new
                        {
                            Id = new Guid("461fa09e-d107-4301-8f72-fc0dfaedb919"),
                            Description = "Description for Product 55",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 55",
                            Price = 564.67m,
                            Stock = 13
                        },
                        new
                        {
                            Id = new Guid("ae6bd903-fa60-48c0-9d63-ee818bb19f45"),
                            Description = "Description for Product 56",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 56",
                            Price = 565.96m,
                            Stock = 94
                        },
                        new
                        {
                            Id = new Guid("b24f420d-9fd7-4fdb-b7cd-af9b50e1b22f"),
                            Description = "Description for Product 57",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 57",
                            Price = 496.29m,
                            Stock = 48
                        },
                        new
                        {
                            Id = new Guid("79a31bf0-e195-4dc9-bc47-7bf586962a6e"),
                            Description = "Description for Product 58",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 58",
                            Price = 801.76m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("d32f5e41-4926-4df0-858f-2efa1a9ce9fb"),
                            Description = "Description for Product 59",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 59",
                            Price = 742.99m,
                            Stock = 62
                        },
                        new
                        {
                            Id = new Guid("f5a9e094-5454-4750-bb27-54b8c8cde681"),
                            Description = "Description for Product 60",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 60",
                            Price = 660.27m,
                            Stock = 54
                        },
                        new
                        {
                            Id = new Guid("b75f4970-2ba3-42a4-8092-b349a25d9b65"),
                            Description = "Description for Product 61",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 61",
                            Price = 518.19m,
                            Stock = 17
                        },
                        new
                        {
                            Id = new Guid("092e3e57-9ceb-448c-95cc-ef10dfb54586"),
                            Description = "Description for Product 62",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 62",
                            Price = 572.54m,
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("c8353168-5a71-4247-9083-9217a3c5ead4"),
                            Description = "Description for Product 63",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 63",
                            Price = 532.70m,
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("3dafb01c-8140-4365-85c8-5774f54e0e7a"),
                            Description = "Description for Product 64",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 64",
                            Price = 157.59m,
                            Stock = 2
                        },
                        new
                        {
                            Id = new Guid("ede9bd29-e7da-4f85-af48-dfc4948faa55"),
                            Description = "Description for Product 65",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 65",
                            Price = 348.08m,
                            Stock = 89
                        },
                        new
                        {
                            Id = new Guid("89f2391b-03aa-42b8-b723-f586dc3501f0"),
                            Description = "Description for Product 66",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 66",
                            Price = 294.06m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("ec2b752a-64d5-4829-8d82-e1c70a1e2aab"),
                            Description = "Description for Product 67",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 67",
                            Price = 827.31m,
                            Stock = 72
                        },
                        new
                        {
                            Id = new Guid("856b34d0-8b9b-4fa9-bd56-7cf03f54f898"),
                            Description = "Description for Product 68",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 68",
                            Price = 874.58m,
                            Stock = 13
                        },
                        new
                        {
                            Id = new Guid("d9f919d1-4c86-4e13-b70a-8f8483e66cee"),
                            Description = "Description for Product 69",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 69",
                            Price = 691.41m,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("cec96b28-03d6-4297-8c80-3f9c030c1ec5"),
                            Description = "Description for Product 70",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 70",
                            Price = 199.81m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("a177697b-bc85-42dc-a241-930758e71532"),
                            Description = "Description for Product 71",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 71",
                            Price = 749.54m,
                            Stock = 23
                        },
                        new
                        {
                            Id = new Guid("6d40207e-8359-4b04-8106-ef77695ea80a"),
                            Description = "Description for Product 72",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 72",
                            Price = 797.06m,
                            Stock = 37
                        },
                        new
                        {
                            Id = new Guid("559a05ec-aa7e-4330-948c-9cdba49638c6"),
                            Description = "Description for Product 73",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 73",
                            Price = 233.71m,
                            Stock = 72
                        },
                        new
                        {
                            Id = new Guid("ae51f95a-b4c3-4bc8-9ed9-8c238c176502"),
                            Description = "Description for Product 74",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 74",
                            Price = 780.02m,
                            Stock = 33
                        },
                        new
                        {
                            Id = new Guid("ce841829-e222-45d4-93b7-8c1158c4212e"),
                            Description = "Description for Product 75",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 75",
                            Price = 679.45m,
                            Stock = 19
                        },
                        new
                        {
                            Id = new Guid("2d7592f1-7dfe-41e3-bfbb-ca88a672355b"),
                            Description = "Description for Product 76",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 76",
                            Price = 578.35m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("18ccfe7f-6721-4b53-bb8e-de2b00b6380b"),
                            Description = "Description for Product 77",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 77",
                            Price = 843.06m,
                            Stock = 78
                        },
                        new
                        {
                            Id = new Guid("6ef463c3-2015-4690-bc94-94398d256630"),
                            Description = "Description for Product 78",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 78",
                            Price = 635.03m,
                            Stock = 54
                        },
                        new
                        {
                            Id = new Guid("45c4c150-f114-4dba-8bd4-a8e02d1c74a7"),
                            Description = "Description for Product 79",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 79",
                            Price = 46.14m,
                            Stock = 1
                        },
                        new
                        {
                            Id = new Guid("5128da86-295a-4423-b450-2a412a3442de"),
                            Description = "Description for Product 80",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 80",
                            Price = 523.47m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("9e61a62b-067b-4718-a03f-21508b4da9cb"),
                            Description = "Description for Product 81",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 81",
                            Price = 828.41m,
                            Stock = 42
                        },
                        new
                        {
                            Id = new Guid("184532c7-350e-4074-b0b4-f2ff46a5746e"),
                            Description = "Description for Product 82",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 82",
                            Price = 937.61m,
                            Stock = 77
                        },
                        new
                        {
                            Id = new Guid("d75d56a9-458e-4643-9f16-6a7b721aa0c7"),
                            Description = "Description for Product 83",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 83",
                            Price = 809.86m,
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("5dbd5b81-f732-4c54-b06d-bba178f31704"),
                            Description = "Description for Product 84",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 84",
                            Price = 557.89m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("d81713f9-95f9-4711-8215-0b012e7f32f8"),
                            Description = "Description for Product 85",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 85",
                            Price = 568.81m,
                            Stock = 55
                        },
                        new
                        {
                            Id = new Guid("caf07902-d1ac-4b72-bf66-60895193d296"),
                            Description = "Description for Product 86",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 86",
                            Price = 431.39m,
                            Stock = 72
                        },
                        new
                        {
                            Id = new Guid("99b798e1-a536-4068-8215-8c1095dd0c65"),
                            Description = "Description for Product 87",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 87",
                            Price = 401.51m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("bce0b0f3-e0e6-4f87-b1a2-e2d2b9b8813a"),
                            Description = "Description for Product 88",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 88",
                            Price = 549.93m,
                            Stock = 64
                        },
                        new
                        {
                            Id = new Guid("30e7a280-f400-428f-9f29-5765d300b697"),
                            Description = "Description for Product 89",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 89",
                            Price = 910.28m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("a4fa6c83-22ba-4912-a5bc-0306c594995e"),
                            Description = "Description for Product 90",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 90",
                            Price = 198.09m,
                            Stock = 92
                        },
                        new
                        {
                            Id = new Guid("fda97bf7-eb42-46a6-a7ea-a5102d3bdfd5"),
                            Description = "Description for Product 91",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 91",
                            Price = 943.11m,
                            Stock = 42
                        },
                        new
                        {
                            Id = new Guid("41342dde-bb7b-40a2-84ff-9d2e10e8adb6"),
                            Description = "Description for Product 92",
                            ImageURL = "https://images.unsplash.com/photo-1580910051070-1d1d17a112ed?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 92",
                            Price = 919.09m,
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("c9eeb650-f0a0-42f4-9618-cd2e4ecca6e5"),
                            Description = "Description for Product 93",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 93",
                            Price = 138.95m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("c4cd304c-1cee-472e-990b-c999944ca825"),
                            Description = "Description for Product 94",
                            ImageURL = "https://images.unsplash.com/photo-1581291519195-ef11498d1cf7?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 94",
                            Price = 13.79m,
                            Stock = 99
                        },
                        new
                        {
                            Id = new Guid("97e4b534-778d-4eca-93f7-2b9ed88408fa"),
                            Description = "Description for Product 95",
                            ImageURL = "https://images.unsplash.com/photo-1512499617640-c2f999b0ed0d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 95",
                            Price = 962.42m,
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("2b894b48-a9b7-42e8-97ce-3dc5c938118a"),
                            Description = "Description for Product 96",
                            ImageURL = "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 96",
                            Price = 102.70m,
                            Stock = 90
                        },
                        new
                        {
                            Id = new Guid("7570839b-a79a-4564-97fc-23bfbfc75aca"),
                            Description = "Description for Product 97",
                            ImageURL = "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 97",
                            Price = 405.96m,
                            Stock = 86
                        },
                        new
                        {
                            Id = new Guid("af8149ca-ad63-4c98-8ab7-158e7b37459c"),
                            Description = "Description for Product 98",
                            ImageURL = "https://images.unsplash.com/photo-1539883379635-9f820d8917f5?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 98",
                            Price = 905.38m,
                            Stock = 23
                        },
                        new
                        {
                            Id = new Guid("822774f9-5c32-4384-bcef-e56351967140"),
                            Description = "Description for Product 99",
                            ImageURL = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 99",
                            Price = 614.15m,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("8caf49f4-527d-423a-aca0-6d1d9755912b"),
                            Description = "Description for Product 100",
                            ImageURL = "https://images.unsplash.com/photo-1581291518837-7f0f8d73d8a4?auto=format&fit=crop&w=200&q=80",
                            Name = "Product 100",
                            Price = 428.20m,
                            Stock = 77
                        });
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.Cart", b =>
                {
                    b.HasOne("Amrod_E_Commerce.Data.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Amrod_E_Commerce.Data.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.CartItem", b =>
                {
                    b.HasOne("Amrod_E_Commerce.Data.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amrod_E_Commerce.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Amrod_E_Commerce.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Amrod_E_Commerce.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amrod_E_Commerce.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Amrod_E_Commerce.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Amrod_E_Commerce.Data.Entities.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
